# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b98799eeae5bea24e35d1c0df16adf3fa4d19ef67362d27b95327dd243cf06bb93d55d6290e74ff041cec01e945a3ba35d33edd311639c37884db05afff9ef25

test:
  secret_key_base: 99c560ca80b71d99c7e03aa24818b48282285c2eac27b88d7b8e1f8f15d42297b2ad9386b57b60f426936ce4a8d314cfd73f4c22402ea76d8a98ce596364d527

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
